### ISSUE TITLE
Автоматическое подключение тезисов

### ISSUE THREAD

**Issue by ijustbsd** [vzms-kmm-vsu/vzms-theses#2]
Можно подключать тезисы автоматически, чтобы не сортировать их вручную.

**Comment by nickkolok** [comment]
Рекомендуется написать скриптик, который бы перечислял тезисы в алфавитном порядке и генерил вспомогательный тех-файл. Сгенерённый тех-файл в гитигнор, ссылку на скрипт в `Makefile`. В принципе, баша должно хватить.
