### ISSUE TITLE
Заголовки статей по шаблону

### ISSUE THREAD

**Issue by ijustbsd** [vzms-kmm-vsu/vzms-theses#3]
Переделать заголовки статей в соответствии с шаблоном:
```tex
\vzmstitle{Название статьи}
\vzmsauthor{Фамилия1}{И1.\,О1.}
\vzmsauthor{Фамилия2}{И2.\,О2.}
\vzmsinfo{Место проживания; {\it Email}}
\vzmscaption
```

**Comment by nickkolok** [comment]
А для гранта отдельной команды нет?

**Comment by ijustbsd** [comment]
Может и есть, но я с ним практически не работал. Мне будет проще Python скриптом отформатировать. Или может вы поищете?

**Comment by nickkolok** [comment]
Я про команду типа \vzmsgrantinfo,  а не про кабанчика.

Нету там ничего такого?

**Comment by nickkolok** [comment]
```
\newcommand{\vzmstitle}[2][]{
	\def\varvzmstitle{#2}
	\def\varvzmstitleopt{#1}
}


```

**Comment by nickkolok** [comment]
Похоже, второй (или первый) необязательный аргумент - сноска на грант.

**Comment by nickkolok** [comment]
Closed by #20
