### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by ijustbsd** [vzms-kmm-vsu/vzms-theses#58]
https://github.com/vzms-kmm-vsu/vzms-theses/blob/a49b38e091c779e95aad48aacc7d50bdaf0e7b85/2022/Data/%D0%90%D0%B2%D0%B4%D0%B5%D0%B5%D0%B2%D0%9D%D0%9D.tex#L12

обычнОЙ?

**Comment by nickkolok** [comment]
Нет. И полуупорядоченность, и норма - обычные. Просто про норму говорится, какая она, а про полуупорядоченность - нет.
