### ISSUE TITLE
Интегральный беспредел

### ISSUE THREAD

**Issue by nickkolok** [vzms-kmm-vsu/vzms-theses#8]
![изображение](https://user-images.githubusercontent.com/5008131/72194447-acbdbb00-341e-11ea-9e9b-550d896e70c5.png)

**Comment by DvaMishkiLapa** [comment]
> Спасибо за вопрос. Нижний предел интеграла равен нулю, верхнего предела нет.
> Но я поставил лишнюю круглую скобку после $B^{x_0}_{2r}$. Пожалуйста, уберите её.
>  
> Ваш Ю. Алхутов.
